'use client';

import { useLanguage } from '@/lib/i18n/LanguageContext';
import { ArrowLeft } from 'lucide-react';
import { useRouter } from 'next/navigation';

export default function TermsPage() {
  var { locale } = useLanguage();
  var router = useRouter();

  var content: Record<string, { title: string; updated: string; sections: { heading: string; body: string }[] }> = {
    ko: {
      title: '이용약관',
      updated: '2025년 3월 8일 시행',
      sections: [
        {
          heading: '제1조 (목적)',
          body: '이 약관은 Seoul AI Travel(이하 "서비스")이 제공하는 인터넷 서비스의 이용조건, 운영자와 이용자의 권리·의무 및 책임사항, 기타 필요한 사항을 규정함을 목적으로 합니다.',
        },
        {
          heading: '제2조 (정의)',
          body: '① "서비스"란 Seoul AI Travel이 운영하는 웹사이트(seoulaitravel.site)를 통해 제공하는 서울 여행 정보, AI 추천, 여행 코스 저장 등의 온라인 서비스를 말합니다.\n② "이용자"란 서비스에 접속하여 이 약관에 따라 서비스를 이용하는 회원 및 비회원을 말합니다.\n③ "회원"이란 서비스에 개인정보를 제공하여 회원등록을 한 자로서, 서비스를 지속적으로 이용할 수 있는 자를 말합니다.',
        },
        {
          heading: '제3조 (약관의 게시 및 변경)',
          body: '① 이 약관은 서비스 화면에 게시하여 공시합니다.\n② 서비스는 관련 법령을 위반하지 않는 범위에서 이 약관을 변경할 수 있으며, 변경된 약관은 적용일자 7일 전부터 공지합니다.\n③ 이용자에게 불리한 약관 변경의 경우 30일 전에 공지합니다.',
        },
        {
          heading: '제4조 (서비스의 내용)',
          body: '서비스는 다음과 같은 기능을 제공합니다.\n① 서울 음식점, 숙소, 관광지 정보 탐색\n② AI 기반 여행 코스 추천\n③ 여행 코스 저장 및 관리\n④ 서울 날씨 및 행사 정보 제공\n⑤ 리뷰 및 찜하기 기능\n⑥ 기타 서비스가 정하는 기능',
        },
        {
          heading: '제5조 (회원가입 및 탈퇴)',
          body: '① 이용자는 서비스가 정한 양식에 따라 회원정보를 기입하고 이 약관에 동의한다는 의사표시를 함으로써 회원가입을 신청합니다.\n② 회원은 언제든지 회원탈퇴를 요청할 수 있으며, 서비스는 즉시 처리합니다.\n③ 만 14세 미만의 아동은 회원가입을 할 수 없습니다.',
        },
        {
          heading: '제6조 (이용자의 의무)',
          body: '이용자는 다음 행위를 하여서는 안 됩니다.\n① 타인의 정보를 도용하여 회원가입하는 행위\n② 서비스의 운영을 방해하는 행위\n③ 서비스를 이용하여 법령 또는 공서양속에 반하는 행위\n④ 타인의 명예를 훼손하거나 불이익을 주는 행위\n⑤ 저작권 등 지적재산권을 침해하는 행위',
        },
        {
          heading: '제7조 (AI 추천 서비스 면책)',
          body: '① AI 추천 코스 및 아티클은 인공지능(Google Gemini)이 생성한 콘텐츠로, 실제 정보와 다를 수 있습니다.\n② 서비스는 AI가 제공하는 정보의 정확성, 완전성, 신뢰성을 보장하지 않습니다.\n③ 이용자는 AI 추천 정보를 참고용으로 활용하며, 이를 근거로 한 행위에 대해 서비스는 책임을 지지 않습니다.\n④ 음식점, 관광지 등의 운영시간, 가격, 위치 등은 변경될 수 있으므로 방문 전 직접 확인하시기 바랍니다.',
        },
        {
          heading: '제8조 (서비스의 변경 및 중단)',
          body: '① 서비스는 운영상 또는 기술상의 필요에 따라 제공하는 서비스를 변경하거나 중단할 수 있습니다.\n② 서비스 중단의 경우 사전에 공지합니다. 다만, 불가피한 사유가 있는 경우 사후에 공지할 수 있습니다.',
        },
        {
          heading: '제9조 (저작권)',
          body: '① 서비스가 작성한 저작물에 대한 저작권은 서비스에 귀속됩니다.\n② AI가 생성한 콘텐츠의 저작권은 관련 법률에 따릅니다.\n③ 이용자가 작성한 리뷰 등의 게시물에 대한 저작권은 해당 이용자에게 귀속됩니다.',
        },
        {
          heading: '제10조 (개인정보보호)',
          body: '서비스는 이용자의 개인정보를 「개인정보 보호법」에 따라 보호하며, 개인정보의 보호 및 사용에 대해서는 별도의 개인정보처리방침을 따릅니다.',
        },
        {
          heading: '제11조 (분쟁해결)',
          body: '① 서비스와 이용자 간에 발생한 분쟁에 대하여는 대한민국 법률을 적용합니다.\n② 서비스 이용으로 발생한 분쟁에 대한 소송은 서비스 운영자의 주소지를 관할하는 법원을 관할법원으로 합니다.',
        },
        {
          heading: '부칙',
          body: '이 약관은 2025년 3월 8일부터 시행됩니다.',
        },
      ],
    },
    en: {
      title: 'Terms of Service',
      updated: 'Effective March 8, 2025',
      sections: [
        {
          heading: 'Article 1 (Purpose)',
          body: 'These Terms govern the conditions of use, rights, obligations, and responsibilities between Seoul AI Travel ("Service") and its users for the internet services provided.',
        },
        {
          heading: 'Article 2 (Definitions)',
          body: '① "Service" refers to online services including Seoul travel information, AI recommendations, and trip course management provided through the website (seoulaitravel.site).\n② "User" refers to both members and non-members who access and use the Service.\n③ "Member" refers to a person who has registered by providing personal information and can continuously use the Service.',
        },
        {
          heading: 'Article 3 (Service Content)',
          body: 'The Service provides the following features:\n① Seoul restaurant, accommodation, and attraction information\n② AI-based travel course recommendations\n③ Trip course saving and management\n④ Seoul weather and event information\n⑤ Reviews and favorites features\n⑥ Other features as determined by the Service',
        },
        {
          heading: 'Article 4 (AI Recommendation Disclaimer)',
          body: '① AI-recommended courses and articles are generated by artificial intelligence (Google Gemini) and may differ from actual information.\n② The Service does not guarantee the accuracy, completeness, or reliability of AI-provided information.\n③ Users should treat AI recommendations as reference material only. The Service is not liable for actions taken based on AI recommendations.\n④ Operating hours, prices, and locations of restaurants and attractions may change. Please verify before visiting.',
        },
        {
          heading: 'Article 5 (Copyright)',
          body: '① Copyright for content created by the Service belongs to the Service.\n② Copyright for AI-generated content follows applicable laws.\n③ Copyright for user-created content (reviews, etc.) belongs to the respective users.',
        },
        {
          heading: 'Article 6 (Privacy)',
          body: 'The Service protects user personal information in accordance with applicable privacy laws. Please refer to our Privacy Policy for details.',
        },
        {
          heading: 'Supplementary',
          body: 'These Terms are effective from March 8, 2025.',
        },
      ],
    },
    ja: {
      title: '利用規約',
      updated: '2025年3月8日施行',
      sections: [
        {
          heading: '第1条（目的）',
          body: 'この規約は、Seoul AI Travel（以下「サービス」）が提供するインターネットサービスの利用条件、運営者と利用者の権利・義務および責任事項、その他必要な事項を規定することを目的とします。',
        },
        {
          heading: '第2条（サービス内容）',
          body: 'サービスは以下の機能を提供します。\n① ソウルのレストラン、宿泊施設、観光地情報\n② AI基盤の旅行コース推薦\n③ 旅行コースの保存と管理\n④ ソウルの天気とイベント情報\n⑤ レビューとお気に入り機能',
        },
        {
          heading: '第3条（AI推薦の免責）',
          body: '① AI推薦コースと記事は人工知能（Google Gemini）が生成したコンテンツであり、実際の情報と異なる場合があります。\n② サービスはAIが提供する情報の正確性、完全性、信頼性を保証しません。\n③ 利用者はAI推薦情報を参考としてご利用ください。',
        },
        {
          heading: '付則',
          body: 'この規約は2025年3月8日から施行されます。',
        },
      ],
    },
    zh: {
      title: '使用条款',
      updated: '2025年3月8日生效',
      sections: [
        {
          heading: '第一条（目的）',
          body: '本条款旨在规定Seoul AI Travel（以下简称"服务"）提供的互联网服务的使用条件、运营者与用户的权利义务及责任事项等必要事项。',
        },
        {
          heading: '第二条（服务内容）',
          body: '服务提供以下功能：\n① 首尔餐厅、住宿、景点信息\n② 基于AI的旅行路线推荐\n③ 旅行路线保存与管理\n④ 首尔天气和活动信息\n⑤ 评价和收藏功能',
        },
        {
          heading: '第三条（AI推荐免责声明）',
          body: '① AI推荐路线和文章是由人工智能（Google Gemini）生成的内容，可能与实际信息有所不同。\n② 服务不保证AI提供信息的准确性、完整性和可靠性。\n③ 用户应将AI推荐信息仅作为参考。',
        },
        {
          heading: '附则',
          body: '本条款自2025年3月8日起生效。',
        },
      ],
    },
  };

  var c = content[locale] || content['ko'];

  return (
    <div className="max-w-2xl mx-auto px-4 py-8">
      <button onClick={function() { router.back(); }} className="flex items-center gap-1 text-sm text-gray-500 hover:text-gray-700 mb-6">
        <ArrowLeft size={16} />
        {locale === 'ko' ? '뒤로' : 'Back'}
      </button>

      <h1 className="text-2xl font-bold text-gray-900 mb-1">{c.title}</h1>
      <p className="text-sm text-gray-400 mb-8">{c.updated}</p>

      <div className="space-y-6">
        {c.sections.map(function(section, i) {
          return (
            <div key={i}>
              <h2 className="font-bold text-gray-900 mb-2">{section.heading}</h2>
              <div className="text-sm text-gray-600 leading-relaxed whitespace-pre-line">
                {section.body}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
